#!/bin/bash

shellType="$1"

cd "$(dirname $0)"
PATH_TO_CONF="$PWD"

CommonFiles=".inputrc .screenrc .vimrc .tmux.conf"
bashFiles=".bash_profile .bashrc .bash_aliases .bash_logout"
zshFiles=".zshrc .zsh_aliases"

case "${shellType:-none}" in
    bash )
        rcFiles="$CommonFiles $bashFiles"
        ;;
    zsh )
        rcFiles="$CommonFiles $zshFiles"
        ;;
    * )
        rcFiles="$CommonFiles $zshFiles $bashFiles"
        ;;
esac

for i in $rcFiles
do
    if [ -f "${PATH_TO_CONF}/dot$i" ]; then
        ln -fs "${PATH_TO_CONF}/dot$i" $HOME/$i
    fi
done

if [ -x /usr/bin/lesskey ]; then
    if [ -f "${PATH_TO_CONF}/dot.lesskey" ]; then
        ln -fs "${PATH_TO_CONF}/dot.lesskey" "$HOME/.lesskey"
        /usr/bin/lesskey
    fi
fi

if [ ! -f "${HOME}/.git-completion.bash" ]; then
    curl -s --output "${HOME}/.git-completion.bash" https://raw.githubusercontent.com/git/git/master/contrib/completion/git-completion.bash
    chmod 644 "${HOME}/.git-completion.bash"
fi

# vim: set ts=4 sw=4 sts=0 et ft=sh fenc=utf-8 ff=unix :
