#!/bin/sh

cd "$(dirname $0)"
PATH_TO_CONF="$PWD"

for i in .bash_profile .bashrc .bash_aliases .bash_logout .inputrc .screenrc .vimrc .tmux.conf
do
    if [ -f "${PATH_TO_CONF}/dot$i" ]; then
        ln -fs "${PATH_TO_CONF}/dot$i" $HOME/$i
    fi
done

if [ -x /usr/bin/lesskey ]; then
    if [ -f "${PATH_TO_CONF}/dot.lesskey" ]; then
        ln -fs "${PATH_TO_CONF}/dot.lesskey" "$HOME/.lesskey"
        /usr/bin/lesskey
    fi
fi

if [ ! -f "${HOME}/.git-completion.bash" ]; then
    curl -s --output "${HOME}/.git-completion.bash" https://raw.githubusercontent.com/git/git/master/contrib/completion/git-completion.bash
    chmod 644 "${HOME}/.git-completion.bash"
fi
